[project]
name = "rag-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bs4>=0.0.2",
    "gradio>=5.8.0",
    "nltk>=3.9.1",
    "openai>=1.56.2",
    "rank-bm25>=0.2.2",
    "requests>=2.32.3",
]
